import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/layout/header";
import Footer from "../components/layout/footer";
import { CartProvider } from "@/context/cartContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f7f7f8] 100vw">
        <Header></Header>

        <div className="max-w-[1040px] mx-auto ">
          <CartProvider>
            
            {children}
          </CartProvider>
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
