import type { Metadata } from "next";
<<<<<<< HEAD
import "./globals.css";
import Header from "../components/layout/header";
import Footer from "../components/layout/footer";
import Searcharea from "../components/layout/searchArea";
=======
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ProductDetails from "@/components/productDetail";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
>>>>>>> 6d2607e (folder)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className="bg-white 100vw">
        <Header></Header>
        <div className="max-w-[1040px] mx-auto">{children}
          <Searcharea/>
        </div>
        <Footer></Footer>
=======
      <body
        className="bg-white 100vw"
      >
        <div className="w-[100vw] h-[100vw] bg-white">
          <Header />
            <div className="max-w-[1440px] mx-auto" >
              {/* //components */}

            </div>

          <Footer />
        </div>
>>>>>>> 6d2607e (folder)
      </body>
    </html>
  );
}
